### ISSUE TITLE
Wifi configuration doesn't propagate to `Nerves.Network.setup()`

### ISSUE THREAD

**Issue by ConnorRigby** [nerves-project/nerves_init_gadget#24]
https://github.com/nerves-project/nerves_init_gadget/blob/master/lib/nerves_init_gadget/network_manager.ex#L22

This means a user can't setup `wlan0`.

**Comment by acrogenesis** [comment]
I'm trying to connect to a WEP network but it won't connect. Using raspbian I can connect using this config:
```
network={
    ssid="wepnetwork"
    key_mgmt=NONE
    wep_key0=weakpassword
    wep_tx_keyidx=0
    priority=1
}
```
I'm trying this in config.ex
```
wlan0: [
    ssid: "wepnetwork",
    wep_key0: "weakpassword",
    key_mgmt: "NONE",
    wep_tx_keyidx: "0"
  ]
```

There seems to be progress using the branch [nerves_network#wpa_settings_update](https://github.com/nerves-project/nerves_network/compare/wpa_settings_update) but I'm getting this error:
```
00:00:14.646 [info]  Start Network Interface Worker
iex(2)> [   15.459946] gpiomem-bcm2835 3f200000.gpiomem: Initialised: Registers at 0x3f200000
00:00:15.463 [info]  [   15.459946] gpiomem-bcm2835 3f200000.gpiomem: Initialised: Registers at 0x3f200000
00:00:16.120 [debug] Elixir.Nerves.Network setup(wlan0, [ipv4_address_method: :dhcp])
iex(2)> [   16.263342] NET: Registered protocol family 10
00:00:16.267 [info]  [   16.263342] NET: Registered protocol family 10
00:00:16.462 [info]  WiFiManager(wlan0) starting
00:00:16.549 [info]  Register Nerves.NetworkInterface "wlan0"
00:00:16.549 [info]  Done Registering
iex(2)> [   16.632654] smsc95xx v1.0.5
00:00:16.625 [info]  [   16.632654] smsc95xx v1.0.5
iex(2)> [   16.694896] brcmfmac: power management disabled
[   16.702734] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
00:00:16.709 [info]  [   16.694896] brcmfmac: power management disabled
00:00:16.709 [info]  [   16.702734] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is n[   16.751264] smsc95xx 1-1.1:1.0 eth0: register 'smsc95xx' at usb-3f980000.usb-1.1, smsc95xx USB 2.0 Ethernet, b8:27:eb:e0:f3:
b5
ot ready
iex(2)> [   16.771981] usbcore: registered new interface driver smsc95xx
00:00:16.762 [info]  [   16.751264] smsc95xx 1-1.1:1.0 eth0: register 'smsc95xx' at usb-3f980000.usb-1.1, smsc95xx USB 2.0 Ethernet, b8:27:eb:e0:f3:b5
00:00:16.762 [info]  [   16.771981] usbcore: registered new interface driver smsc95xx
00:00:16.909 [info]  nerves_network_interface received :ifchanged and %{ifname: "wlan0", index: 2, is_broadcast: true, is_lower_up: false, is_multicast: true, is_running: true, is_up: true, mac_address: "b8
:27:eb:b5:a6:e0", mac_broadcast: "ff:ff:ff:ff:ff:ff", mtu: 1500, operstate: :unknown, stats: %{collisions: 0, multicast: 0, rx_bytes: 0, rx_dropped: 0, rx_errors: 0, rx_packets: 0, tx_bytes: 0, tx_dropped: 
0, tx_errors: 0, tx_packets: 0}, type: :ethernet}
00:00:16.911 [info]  nerves_network_interface received :ifchanged and %{ifname: "wlan0", index: 2, is_broadcast: true, is_lower_up: false, is_multicast: true, is_running: false, is_up: true, mac_address: "b
8:27:eb:b5:a6:e0", mac_broadcast: "ff:ff:ff:ff:ff:ff", mtu: 1500, operstate: :down, stats: %{collisions: 0, multicast: 0, rx_bytes: 0, rx_dropped: 0, rx_errors: 0, rx_packets: 0, tx_bytes: 0, tx_dropped: 0,
 tx_errors: 0, tx_packets: 0}, type: :ethernet}
00:00:16.912 [info]  nerves_network_interface received :ifadded and %{ifname: "eth0", index: 3}
00:00:16.914 [info]  nerves_network_interface received :ifchanged and %{ifname: "eth0", index: 3, is_broadcast: true, is_lower_up: false, is_multicast: true, is_running: false, is_up: false, mac_address: "b
8:27:eb:e0:f3:b5", mac_broadcast: "ff:ff:ff:ff:ff:ff", mtu: 1500, operstate: :down, stats: %{collisions: 0, multicast: 0, rx_bytes: 0, rx_dropped: 0, rx_errors: 0, rx_packets: 0, tx_bytes: 0, tx_dropped: 0,
 tx_errors: 0, tx_packets: 0}, type: :ethernet}
00:00:17.032 [info]  WiFiManager(wlan0) network_interface ifup
00:00:17.037 [info]  Nerves.NetworkInterface - WiFiManager(wlan0, down) got event :ifup
00:00:17.078 [info]  WiFiManager(wlan0) starting
00:00:17.078 [info]  Register Nerves.NetworkInterface "wlan0"
00:00:17.078 [info]  Done Registering
00:00:17.091 [info]  WiFiManager(wlan0) network_interface ifup
00:00:17.105 [info]  Nerves.NetworkInterface - WiFiManager(wlan0, down) got event :ifup
00:00:17.145 [info]  nerves_network_interface received :ifchanged and %{ifname: "wlan0", index: 2, is_broadcast: true, is_lower_up: false, is_multicast: true, is_running: false, is_up: true, mac_address: "b
8:27:eb:b5:a6:e0", mac_broadcast: "ff:ff:ff:ff:ff:ff", mtu: 1500, operstate: :down, stats: %{collisions: 0, multicast: 0, rx_bytes: 0, rx_dropped: 0, rx_errors: 0, rx_packets: 0, tx_bytes: 0, tx_dropped: 0,
 tx_errors: 0, tx_packets: 0}, type: :ethernet}
00:00:17.304 [info]  nerves_network_interface received :ifchanged and %{ifname: "wlan0", index: 2, is_broadcast: true, is_lower_up: false, is_multicast: true, is_running: false, is_up: true, mac_address: "b
8:27:eb:b5:a6:e0", mac_broadcast: "ff:ff:ff:ff:ff:ff", mtu: 1500, operstate: :down, stats: %{collisions: 0, multicast: 0, rx_bytes: 0, rx_dropped: 0, rx_errors: 0, rx_packets: 0, tx_bytes: 0, tx_dropped: 0,
 tx_errors: 0, tx_packets: 0}, type: :ethernet}
00:00:17.424 [info]  WiFiManager(wlan0) starting
00:00:17.424 [info]  Register Nerves.NetworkInterface "wlan0"
00:00:17.424 [info]  Done Registering
00:00:17.444 [info]  WiFiManager(wlan0) network_interface ifup
00:00:17.449 [info]  Nerves.NetworkInterface - WiFiManager(wlan0, down) got event :ifup
00:00:17.898 [info]  Register Nerves.WpaSupplicant "wlan0"
00:00:18.131 [info]  Nerves.WpaSupplicant: sending 'REMOVE_NETWORK all'
00:00:18.421 [info]  Nerves.WpaSupplicant: sending 'ADD_NETWORK'
00:00:18.422 [info]  Nerves.WpaSupplicant: sending 'SET_NETWORK 0 ipv4_address_method dhcp'
00:00:18.484 [info]  WiFiManager(wlan0, down) wpa_supplicant set_network error: {:error, :ipv4_address_method, :FAIL}
        
00:00:18.484 [info]  WiFiManager(wlan0): ignoring event: {:error, :ipv4_address_method, :FAIL}
        
00:00:18.485 [info]  Nerves.WpaSupplicant - WiFiManager(wlan0, associate_wifi) got event :noop
        
00:00:18.630 [error] GenServer :"Nerves.Network.Interface.wlan0" terminating
** (MatchError) no match of right hand side value: {"Successfully initialized wpa_supplicant\nctrl_iface exists and seems to be in use - cannot override it\nDelete '/var/run/wpa_supplicant/wlan0' manually if it is not used anymore\nFailed to initialize control interface '/var/run/wpa_supplicant'.\nYou may have another wpa_supplicant process already running or the file was\nleft by an unclean termination of wpa_supplicant in which case you will need\nto manually remove this file before starting wpa_supplicant again.\n\nnl80211: deinit ifname=wlan0 disabled_11b_rates=0\n", 255}
    (nerves_network) lib/nerves_network/wifi_manager.ex:357: Nerves.Network.WiFiManager.start_wpa/1
    (nerves_network) lib/nerves_network/wifi_manager.ex:252: Nerves.Network.WiFiManager.consume/3
    (nerves_network) lib/nerves_network/wifi_manager.ex:215: Nerves.Network.WiFiManager.handle_info/2
    (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: {Nerves.NetworkInterface, :ifchanged, %{ifname: "wlan0", index: 2, is_broadcast: true, is_lower_up: false, is_multicast: true, is_running: false, is_up: true, mac_address: "b8:27:eb:b5:a6:e0", mac_broadcast: "ff:ff:ff:ff:ff:ff", mtu: 1500, operstate: :down, stats: %{collisions: 0, multicast: 0, rx_bytes: 0, rx_dropped: 0, rx_errors: 0, rx_packets: 0, tx_bytes: 0, tx_dropped: 0, tx_errors: 0, tx_packets: 0}, type: :ethernet}}
State: %Nerves.Network.WiFiManager{context: :down, dhcp_pid: nil, ifname: "wlan0", settings: [ipv4_address_method: :dhcp], wpa_pid: nil}
```
